### ISSUE TITLE
Allowed memory size of 1GB bytes exhausted

### ISSUE THREAD

**Issue by Nyholm** [Roave/BackwardCompatibilityCheck#107]
This issue is just an FYI. Feel free to close if it is irrelevant.

I [ran this tool on Travis](https://travis-ci.org/php-translation/symfony-bundle/jobs/423578346) for php-translation/symfony-bundle and I got an error telling me I'm using too much memory. 

Im not sure if there is a fix to this library or if I just should increase the memory limit.

**Comment by Ocramius** [comment]
Moving to generators may aid this, but I think this memory usage is normal, as everything is memorized on purpose. See: https://github.com/Roave/BackwardCompatibilityCheck/blob/2.0.0/src/Factory/DirectoryReflectorFactory.php#L42

**Comment by Ocramius** [comment]
Closing here: verified that this is unavoidable unless a non-memoizing reflector and parser are used: in those cases, execution times may go up excessively, rendering the tool unusable anyway.
