### ISSUE TITLE
[idea] Add command line option to skip empty sections

### ISSUE THREAD

**Issue by goetas** [Roave/BackwardCompatibilityCheck#112]
What about adding an option that skips empty sections when dumping changelog to markdown?

Example, lets suppose one method has been removed and one added but no methods have been changed, currently we get:

```
# Added
 - bla bla
# Changed

# Removed
 - bla bla
```

The expected result could be 

```
# Added
 - bla bla

# Removed
 - bla bla
```

**Comment by Ocramius** [comment]
Right now, there is no such thing as a "report" that is rendered, but rather one huge iterator that is lazily traversed, so this isn't possible without an architectural change.

We should, IMO, abstract the report into a separate sub-component that handles this, which would allow printing the BC information by providing any instance of the reporting component.

**Comment by goetas** [comment]
Right! For now I have solved it with a dirty regex, but except of that works like a charm!

**Comment by Ocramius** [comment]
TBH, as discussed also with @Majkl578, the aim to make "reports" went a lot out of focus, while the focus was mostly towards detecting and rejecting BC breaks (with an exit code). Would it be a good idea to add a second CLI script that is NOT designed to fail/exit with non-zero status code, only used for reporting purposes?

**Comment by goetas** [comment]
IMO having two cli could be not the best idea... one of the two will endup being un-maintained, or there will be diffs in how exit codes are handled.

IMO adding a option --format=none could be already good enough.

**Comment by Ocramius** [comment]
Closing as duplicate #39, which effectively asks for a way to generate a BC report.
