### ISSUE TITLE
Error: tmp/api-compare ... was expected to exist.

### ISSUE THREAD

**Issue by schmunk42** [Roave/BackwardCompatibilityCheck#115]
Due to https://github.com/Roave/BackwardCompatibilityCheck/issues/114, I tried to run the check command with `--from` and `--to`, but I got an error:

```
root@415101e15410:/repo# vendor/bin/roave-backward-compatibility-check --from=2.4.0 --to=2.6.1
Comparing from 06194f705c3e967fb8665060f0afb482495a88f9 to 613821a6b0b805aa8fddc0d47b0ab6bb3a3e0456...
Loading composer repositories with package information
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for yiisoft/yii2-composer 2.0.3 -> satisfiable by yiisoft/yii2-composer[2.0.3].
    - yiisoft/yii2-composer 2.0.3 requires composer-plugin-api 1.0.0 -> no matching package found.
  Problem 2
    - yiisoft/yii2-composer 2.0.3 requires composer-plugin-api 1.0.0 -> no matching package found.
    - yiisoft/yii2 2.0.6 requires yiisoft/yii2-composer * -> satisfiable by yiisoft/yii2-composer[2.0.3].
    - Installation request for yiisoft/yii2 2.0.6 -> satisfiable by yiisoft/yii2[2.0.6].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

In Assertion.php line 288:
                                                                                                                                      
  File "/tmp/api-compare-06194f705c3e967fb8665060f0afb482495a88f9_5c4f17f2f12c4/vendor/composer/autoload_..." was expected to exist.  
                                                                                                                                      

roave-backwards-compatibility-check:assert-backwards-compatible [--from [FROM]] [--to TO] [--format [FORMAT]]
```

Note: I am running this in a Docker container, but the whole repo is available in the container.

**Comment by Ocramius** [comment]
Does this apply to any --from you tried so far?

**Comment by schmunk42** [comment]
For this repo, yes.

**Comment by Ocramius** [comment]
Hmm, wondering why `composer-plugin-api` wouldn't exist in that scenario. @alcohol can I bother you for questions about this?

We're running composer directly (not via CLI) by using the `Installer`:

https://github.com/Roave/BackwardCompatibilityCheck/blob/459e15befca19a2100b5f8e9c72a01f52c9c634d/bin/roave-backward-compatibility-check.php#L69-L77

Any pointers on whether the environment is different in that context would be very useful

**Comment by alcohol** [comment]
Oef, that involves the plugin API, and @seldaek knows much more about that than I do.

**Comment by alcohol** [comment]
Oh, right, because it's hardcoded in the Composer source so if you're using a recent version of Composer there simply is no way we could ever fulfill the constraint for `1.0.0`.

**Comment by Ocramius** [comment]
Aha, interesting!

@schmunk42 can you check if `roave/backwards-compatibility-check` is installable with a requirement of `"composer-plugin-api": "1.0.0"` please? Otherwise, this needs to go back to the upstream library.

**Comment by Ocramius** [comment]
Thanks @alcohol, @Seldaek!

**Comment by schmunk42** [comment]
I can not install this

```
{
    "require": {
        "roave/backward-compatibility-check": "^2.0",
        "composer-plugin-api": "1.0.0"
    }
}
```

Error:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package composer-plugin-api 1.1.0 is satisfiable by composer-plugin-api[1.1.0] but these conflict with your requirements or minimum-stability.
  Problem 2
    - The requested package composer-plugin-api 1.0.0 exists as composer-plugin-api[1.1.0] but these are rejected by your constraint.
```

---

Another question: Would it be possible in general to create a `roave-backward-compatibility-check.phar` to avoid such issues?

I was also trying to run `roave-backward-compatibility-check` from a separate installation (vendor folder) for debugging.

**Comment by Ocramius** [comment]
> Would it be possible in general to create a `roave-backward-compatibility-check.phar` to avoid such issues?

Not really, since the installation of the packages (for diffing purposes) is required.

If you use this:

```json
{
    "require": {
        "roave/backward-compatibility-check": "^2.0",
        "composer-plugin-api": "1.0.0"
    }
}
```

Then you must also run an installation of an older version of `composer.phar` itself.

**Comment by alcohol** [comment]
Why not just change the constraint for `composer-plugin-api` to `^1.0` ?

**Comment by alcohol** [comment]
You simply cannot require `composer-plugin-api` at `1.0.0` since Composer release `1.1.0`, which is incredibly old, so this makes me wonder what version you've been using all this time.

**Comment by schmunk42** [comment]
I think my initial problems came from the fact that there's a lock file in older versions of my lib, see https://github.com/dmstr/yii2-adminlte-asset/blob/b339611f9f34621d731d3feca3a83b42720c7d5c/composer.lock#L631-L632

So maybe it's just not possible to BC-check those old versions.

**Comment by alcohol** [comment]
It is, if you use a really old version of Composer.
