### ISSUE TITLE
Running out of memory

### ISSUE THREAD

**Issue by nschoellhorn** [Roave/BackwardCompatibilityCheck#119]
The BC checker runs out of memory when running against the current master of [Ocramius/LazyProperty](https://github.com/Ocramius/LazyProperty), checking against 2.0.0. I talked to Marco already and he thinks it might be due to too much json metadata being downloaded for the packages.

I have attached the output of the run that failed. After that, I bumped my memory_limit to 2G, which went fine. Putting it back down to the initial 128M and running the BC checker again did not lead to a crash, so it's very likely that it has to do with some kind of caching being built.

https://gist.github.com/mrpixeldream/7b8f9ab249c30f4870bc477380c1b50c

**Comment by Ocramius** [comment]
Looking at where the traces go, this seems to be caused by composer internals downloading JSON packages, not by this package directly. The fact that a filesystem cache prevents this could indicate that the downloader needs more magic. What this highlights, though, is that the composer system cache is being used,  which should probably be disabled overall.

BTW, I think 128Mb for CLI tools (at least most CLI tool written in PHP) is too little.

**Comment by Ocramius** [comment]
This is to be re-assessed after #120 - memory usage should be going massively down after that.

**Comment by Ocramius** [comment]
Seems fixed.

Before:

```
38 backwards-incompatible changes detected
Command exited with non-zero status 3
	Command being timed: "bin/roave-backward-compatibility-check r:a --from=v2.7.2 --to=v2.8.0"
	User time (seconds): 180.28
	System time (seconds): 2.47
	Percent of CPU this job got: 96%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 3:08.70
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 434160
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 147961
	Voluntary context switches: 701
	Involuntary context switches: 7326
	Swaps: 0
	File system inputs: 32
	File system outputs: 36336
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 3

```

After:

```
Command exited with non-zero status 3
	Command being timed: "bin/roave-backward-compatibility-check r:a --from=v2.7.2 --to=v2.8.0"
	User time (seconds): 11.50
	System time (seconds): 0.38
	Percent of CPU this job got: 90%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:13.18
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 152536
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 67577
	Voluntary context switches: 771
	Involuntary context switches: 1071
	Swaps: 0
	File system inputs: 0
	File system outputs: 35840
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 3
```

Memory usage is massively reduced :+1:
