### ISSUE TITLE
Remove version limitations from phar assembly tool

### ISSUE THREAD

**Issue by Ocramius** [Roave/BackwardCompatibilityCheck#159]
See https://github.com/Roave/BackwardCompatibilityCheck/blob/5092098994e3de84300a71c997494d6f637e839d/build-phar.sh#L7-L9

That is wrong, since:

 1. we will run the phar assembly on the correct version
 2. we shouldn't `composer update`, but rather `composer install --no-dev`
 3. script should completely bail out in case of errors

**Comment by Ocramius** [comment]
As per https://github.com/Roave/BackwardCompatibilityCheck/issues/157#issuecomment-532618696, box should also be upgraded

**Comment by Ocramius** [comment]
Note: we should probably install `box` via composer, so we are always on latest stable.

**Comment by darenas31415** [comment]
Hi @Ocramius,

I've played with this a little bit.

Adding hambug/box to the main composer.json doesn't work after running composer install with --no-dev therefore moving the script to the build directory and creating a new composer.json there with only hambug/box.

I've seen other projects using bamarni/composer-bin-plugin to isolate and avoid conflicts on plugins.

Let me know if you prefer that approach, I can quickly make the changes and open a PR.

Thanks

**Comment by Ocramius** [comment]
Wouldn't a new tmp directory with `composer require humbug/box` work?

**Comment by darenas31415** [comment]
Yeah, that works perfectly and removes the composer.json boilerplate 👍
