### ISSUE TITLE
Classes with @internal should be skipped

### ISSUE THREAD

**Issue by goetas** [Roave/BackwardCompatibilityCheck#160]
This is feature request.

Is there planned (or is it possible) to exclude from the BC brak report classes marked as `@internal`? They are not BC breaks since they are not covered by the BC promise.

**Comment by asgrim** [comment]
Hmm, I believe this was already merged in for release `4.0.0` (see #141) - what version are you using?

**Comment by goetas** [comment]
The one provided buy `docker run --rm -v `pwd`:/app nyholm/roave-bc-check`, let me try with 4.0

**Comment by goetas** [comment]
`4.x` works nice! 

@Nyholm It seems `nyholm/roave-bc-check:latest` does not target the latest version.

**Comment by Nyholm** [comment]
`nyholm/roave-bc-check:latest` is dev-master
`nyholm/roave-bc-check:stable` is the latest tagged release 

Are you sure you cannot solve this issue by pulling `nyholm/roave-bc-check:latest` again?

**Comment by Nyholm** [comment]
I've turned off "build cache" on Dockerhub. That might have been an issue. In a few hours (when dockerhub finally built the images again) there should not be any more issues. 

@goetas could you please confirm?

**Comment by goetas** [comment]
@Nyholm A fresh docker pull of latest refreshed the docker image and now works. So build cache to blame!

**Comment by asgrim** [comment]
Thanks folks, glad it's sorted! :+1:
