### ISSUE TITLE
Add option to install `require-dev` dependencies when analyzing a codebase

### ISSUE THREAD

**Issue by Nyholm** [Roave/BackwardCompatibilityCheck#203]
I currently have a problem with some libraries using test files in their source. That will give me plenty of
```
[BC] SKIPPED: Roave\BetterReflection\Reflection\ReflectionClass "PHPUnit\Framework\TestCase" could not be found in the located source
```
For this specific case it is the `psr/log` package. ([my package](https://github.com/async-aws/core/runs/474557373?check_suite_focus=true#step:4:31))

I have been hacking the output before. See how [I did in Guzzle](https://github.com/guzzle/guzzle/blob/7.0.0-beta.1/.github/workflows/bc.entrypoint). I dont feel this is the way I should go about it though...

I would like to add these suppress messages in a config file some how.

**Comment by Ocramius** [comment]
Potentially duplicate of https://github.com/Roave/BackwardCompatibilityCheck/issues/77

**Comment by asgrim** [comment]
@Nyholm would #319 help this issue perhaps?

**Comment by asgrim** [comment]
OK; so not quite the best solution :) I'm ok to leave this issue open as a possible improvement.
