### ISSUE TITLE
Please, update thecodingmachine/safe

### ISSUE THREAD

**Issue by KartaviK** [Roave/BackwardCompatibilityCheck#210]
I use 1.0 version, but minimum required in your package is 0.1, please, if you can, update it)

```bash
roave/backward-compatibility-check 4.4.0 requires thecodingmachine/safe ^0.1.16 -> satisfiable by thecodingmachine/safe[0.1.x-dev, v0.1.16] but these conflict with your requirements or minimum-stability.
```

**Comment by Ocramius** [comment]
@KartaviK send a patch for inclusion in `5.0.0`, please :+1:

**Comment by KartaviK** [comment]
There is a problem with infection/infection. They dont have thecodingmachine/safe 1.0 too

**Comment by Ocramius** [comment]
Ah yep, I remember trying to upgrade. See https://github.com/infection/infection/releases/tag/0.15.3

If you bump both, we should be good.

**Comment by jdreesen** [comment]
They have in `v0.15.3`. You need to update it as well.

**Comment by KartaviK** [comment]
PR: https://github.com/Roave/BackwardCompatibilityCheck/pull/211

**Comment by Ocramius** [comment]
Thanks, @KartaviK!
