### ISSUE TITLE
bc breaking changes are not detected

### ISSUE THREAD

**Issue by staabm** [Roave/BackwardCompatibilityCheck#216]
first things first: great tool, I hope we can use it in the near future wihtin our CI pileline <3.

I do some local tests with the bc tool, but cannot get it to detect BC breaking changes.

my setup:
- local codebase from a private github repo
- created a branch for testing
- fake some BC breaking changes, by dropping public properties and public methods from a few classes involved
- committed the changes into my testing branch
- run `roave-backward-compatibility-check --from=f0ebb39b551ef582db02d6759815a6aa31cdad04` using the base-git ref from the branch (since we dont have semver)
-> the tool is reporting: `No backwards-incompatible changes detected` 
(I can see the tool running, checking out the different revisions, running the composer build etc,... so it seems to work in my eyes)

env:
- windows10x64
- php 7.4.3

I was wondering..
- can BC breaks only be detected when changes are committed?
- can BC breaks only be detected for classes which are reachable via the composer autoloader? (the readme mentions that dependencies need to be managed via composer, but does not mention autoloading)
- can BC breaks only be detected in namespaced code?

**Comment by Ocramius** [comment]
> can BC breaks only be detected when changes are committed?

Yes, although you can implement your own logic to extract sources and dependencies from a project.

> can BC breaks only be detected for classes which are reachable via the composer autoloader? (the readme mentions that dependencies need to be managed via composer, but does not mention autoloading)

Yes, specifically `"autoload"` section of `composer.json`

> can BC breaks only be detected in namespaced code?

No, just need to have the code under the `"autoload"` section of `composer.json`: shouldn't need to be namespaced.

Note that this design is necessary: autoloading any symbols is unsafe and unfeasible due to static type collisions otherwise.

**Comment by staabm** [comment]
thx for the fast feedback.

could you give me a hint on how to at best figure out, why my BC breaking changes are not detected right now? some kind of debugging feature or similar?

**Comment by Ocramius** [comment]
Would need to see the project, but also check what the BC checker understands as "sources".

That is done by these two dependencies: https://github.com/Roave/BackwardCompatibilityCheck/blob/4.4.0/bin/roave-backward-compatibility-check.php#L64
