### ISSUE TITLE
Support `roave/better-reflection` `^4.0`

### ISSUE THREAD

**Issue by Levivb** [Roave/BackwardCompatibilityCheck#234]

**Comment by Ocramius** [comment]
please send a patch: should be a straightforward change, I suppose?

**Comment by tomasnorre** [comment]
There is already an automated PR for this or I assume that it's automated, looks like it. 
https://github.com/Roave/BackwardCompatibilityCheck/pull/238

**Comment by tomasnorre** [comment]
The tests are failing in the PR, probably the reason a good reason, why it isn't merged yet. 
The tests in master are also failing locally in my setup. 

I haven't really looked into why yet.

**Comment by Ocramius** [comment]
Yup, some work needed there to adjust the major BC Breaks.

Anyone willing to send a patch? Unable to do so this week...

**Comment by tomasnorre** [comment]
I'm not sure what needs to be done, as it's the first time I hear about this package today.

**Comment by tomasnorre** [comment]
I also have `psalm` errors with master. :)

**Comment by Ocramius** [comment]
O_o that shouldn't be the case... unless we have newer dependency changes.

Should probably use locked dependencies for running SA/CS checks (will do when switching to github actions)

**Comment by tomasnorre** [comment]
Both phpunit and psalm fails locally for me.

**Comment by Ocramius** [comment]
Hmm, ok, then I guess some dependency changes did break everything :\

Will investigate next week, if I get to it :+1:

**Comment by tomasnorre** [comment]
Haven't checked with git bisect yet, but the 4.4.0 tag is also failing with phpunit and psalm locally by me.

**Comment by Jean85** [comment]
Build should be fixed by #247, issue fixed by #248
