### ISSUE TITLE
Support for safe 1.x in 4.x branch

### ISSUE THREAD

**Issue by WyriHaximus** [Roave/BackwardCompatibilityCheck#242]
Are you open for supporting thecodingmachine/safe 1.x in the 4.x version?

**Comment by Ocramius** [comment]
I think it's worth doing a new release after we managed to bump all dependencies: hopefully this coming week.

**Comment by WyriHaximus** [comment]
Assuming you're talking about `5.0.0`?

**Comment by Ocramius** [comment]
Yup.

Consider that the BC breaks are mostly due to inherited API, not
CLI/behaviour changes

**Comment by WyriHaximus** [comment]
Awesome! Looking forward to it :D. Quick final question, does this package support JSON output? As in `vendor/bin/roave-backward-compatibility-check --format=json`?

**Comment by Ocramius** [comment]
At this moment, no json support.

I think it may make sense to use a standard format such as JUnit or checkstyle though?

**Comment by WyriHaximus** [comment]
As long as I can parse it I don't care about the format, it's just that markdown isn't a really useful format to use in an automated environment 😂 . Looking into automating what milestone to attach to a PR depending on if the PR does a breaking change or not.

**Comment by Ocramius** [comment]
That would be told by the exit code right now, but I agree that it is
useful to have a machine-friendly format 👍

**Comment by WyriHaximus** [comment]
Sweet thanks, will have a look at `5.0.0` once it comes out 👍

**Comment by Ocramius** [comment]
Seems like the failures on `master` are due to PHP 7.4.6, which has some very nasty bugs in `yield from`.

I think a release will require a `"conflict": {"php": "7.4.6"}` for now.
