### ISSUE TITLE
Fatal: ambiguous argument '${env.GIT_COMMIT}': unknown revision or path not in the working tree

### ISSUE THREAD

**Issue by pawan22sfdl** [Roave/BackwardCompatibilityCheck#255]
Hello Github People

I am facing a issue while running a differential deployment groovy code from jenkins for salesforce build.

**My Groovy code :-**

<project>
<taskdef resource="net/sf/antcontrib/antlib.xml">
		<classpath>
			<pathelement location="lib/ant-contrib-1.0b3.jar"/>
		</classpath>
</taskdef>
<macrodef name="gitDiff">
		<sequential>
			<exec executable="git" outputproperty="git.diff">
				<arg value="diff" />
				<arg value="--pretty=format:" />
				<arg value="--name-only" />
				<arg value="${env.GIT_COMMIT}" />
				<arg value="${env.GIT_PREVIOUS_SUCCESSFUL_COMMIT}" />
			</exec>
			<echo>${git.diff}</echo>
		</sequential>
</macrodef>

<target name="diffBuilderWithGitCommit">
		<delete dir="deploy-sf"/>
		<mkdir dir="deploy-sf"/>
		<echo>Current GIT Commit : ${env.GIT_COMMIT}</echo>
		<echo>Previous Known Successful GIT Commit : ${env.GIT_PREVIOUS_SUCCESSFUL_COMMIT}</echo>
		<gitDiff/>
		<for list="${git.diff}" param="currentDiff" delimiter="${line.separator}">
			<sequential>
				<if>
					<and>
						<available file="@{currentDiff}"/>
						<matches string="@{currentDiff}" pattern="force-app/"/>
					</and>
					<then>
						<propertyregex
							property="currentDiffWithoutSRC"
							input="@{currentDiff}"
							regexp="force-app\/([a-zA-Z$]*\/[a-zA-Z0-9\/\.\_-]*)"
							select="\1"
							casesensitive="true" 
							override="true"
							defaultValue=""/>
						<echo>Current Component : ${currentDiffWithoutSRC}</echo>
						<copy todir="deploy-sf" verbose="false">
							<fileset dir="force-app">
								<include name="${currentDiffWithoutSRC}" />
							</fileset>
						</copy>
						<if>
							<available file="@{currentDiff}-meta.xml"/>
							<then>
								<echo>Generating meta-xml : @{currentDiff}</echo>
								<copy todir="deploy-sf" verbose="false">
									<fileset dir="force-app">
										<include name="${currentDiffWithoutSRC}-meta.xml" />
									</fileset>
								</copy>
							</then>
						</if>
					</then>
				</if>
			</sequential>
		</for>
</target>
</project>

**Error I am Getting** 

diffBuilderWithGitCommit:
   [delete] Deleting directory C:\Program Files (x86)\Jenkins\workspace\GitDiff\deploy-sf
    [mkdir] Created dir: C:\Program Files (x86)\Jenkins\workspace\GitDiff\deploy-sf
     [echo] Current GIT Commit : ${env.GIT_COMMIT}
     [echo] Previous Known Successful GIT Commit : ${env.GIT_PREVIOUS_SUCCESSFUL_COMMIT}
     [exec] Result: 128
     **[echo] fatal: ambiguous argument '${env.GIT_COMMIT}': unknown revision or path not in the working tree.
     [echo] Use '--' to separate paths from revisions, like this:
     [echo] 'git <command> [<revision>...] -- [<file>...]'**

**Comment by asgrim** [comment]
Hello @pawan22sfdl - I'm not sure what this has to do with this tool? Are you actually using Roave Backward compatibility checker...? None of the output is from this tool...

**Comment by pawan22sfdl** [comment]
@asgrim no but i am using simple jenkins and a groovy script with any build capability

I dont know what is roave backward compatability checker?

For these lines of code :-

<target name="diffBuilderWithGitCommit">
		<delete dir="deploy-sf"/>
		<mkdir dir="deploy-sf"/>
		<echo>Current GIT Commit : ${env.GIT_COMMIT}</echo>
		<echo>Previous Known Successful GIT Commit : ${env.GIT_PREVIOUS_SUCCESSFUL_COMMIT}</echo>
		<gitDiff/>
		<for list="${git.diff}" param="currentDiff" delimiter="${line.separator}">

Getting below error

diffBuilderWithGitCommit:
   [delete] Deleting directory C:\Program Files (x86)\Jenkins\workspace\GitDiff\deploy-sf
    [mkdir] Created dir: C:\Program Files (x86)\Jenkins\workspace\GitDiff\deploy-sf
     [echo] Current GIT Commit : ${env.GIT_COMMIT}
     [echo] Previous Known Successful GIT Commit : ${env.GIT_PREVIOUS_SUCCESSFUL_COMMIT}
     [exec] Result: 128
     [echo] fatal: ambiguous argument '${env.GIT_COMMIT}': unknown revision or path not in the working tree.
     [echo] Use '--' to separate paths from revisions, like this:
     [echo] 'git <command> [<revision>...] -- [<file>...]'

**Comment by asgrim** [comment]
@pawan22sfdl You have reported an issue with a tool called Roave/BackwardCompatibilityCheck (see the URL?); perhaps try contacting Jenkins commercial support? https://wiki.jenkins.io/display/JENKINS/Commercial+Support

**Comment by asgrim** [comment]
@pawan22sfdl also, maybe try googling the error you're seeing, it seems to have some results that may help, although I can't say for sure since this absolutely nothing to do with Roave/BackwardCompatibilityCheck tool (which you are not using) :grin: : https://www.google.com/search?client=firefox-b-d&q=fatal%3A+ambiguous+argument+%27%24%7Benv.GIT_COMMIT%7D%27%3A+unknown+revision+or+path+not+in+the+working+tree. Best of luck finding the right solution :)
