### ISSUE TITLE
Parse error on 5.x 

### ISSUE THREAD

**Issue by Nyholm** [Roave/BackwardCompatibilityCheck#267]
Running the BC checker on nyholm/psr7 result in: 

> [BC] SKIPPED: AST failed to parse in located source (in /private/var/folders/hw/xb7mf0_5453d0bqt970t1mkh0000gn/T/api-compare-c17f4f73985f62054a331cbc4ffdf9868c4ef256_5f6dc01b8cb8d/src/MessageTrait.php)

It works fine with 4.x and I cannot figure out why that class cannot be parsed.

**Comment by Ocramius** [comment]
Hmm, traits can be tricky (generally suggest to avoid them, but heh, here we are).

I would suggest looking at the backtrace in https://github.com/Roave/BackwardCompatibilityCheck/blob/8a3d4a38369d5dcdf1590e031ac822d52e057677/src/DetectChanges/BCBreak/TraitBased/SkipTraitBasedErrors.php#L26

**Comment by Nyholm** [comment]
I've spent some time debugging this now. It is not related to `SkipTraitBasedErrors`. It is related to https://github.com/nikic/PHP-Parser/issues/710

I get a TypeError

> addcslashes() expects parameter 1 to be string, null given
> vendor/nikic/php-parser/lib/PhpParser/PrettyPrinter/Standard.php:984

Somehow, a `String_` get a null value. 

I think it is because of the `MemoizingParser` in BetterReflecetion
