### ISSUE TITLE
Question: could not locate vendor/composer/installed.json 

### ISSUE THREAD

**Issue by tomasnorre** [Roave/BackwardCompatibilityCheck#271]
Hi, 

I'm currently trying out this tool, to help me learn more about breaking changes. 

I have project that isn't setup like standard PHP like: 

`src/`, `vendor` etc. 

And I saw that it was a problem for this tool as expecting folders like that. 
I have added this to my Github actions:

And before running the `vendor/bin/roave-backward-compatibility-check` I've done: 
```shell
composer config vendor-dir vendor
composer config bin-dir vendor/bin
composer install
```

But I still get this error:
```shell
Could not locate a "vendor/composer/installed.json" file in "/tmp/api-compare-a2776c9aaedd51764993b311f6d0570092c25c19_5fcfcb63ec  
  d2a"
```  

I'm not sure yet but my theory is that the `vendor/bin/roave-backward-compatibility-check` checks out the last minor e.g. 9.1.0 and run a composer install on that and as I don't have the correct vendor structure it didn't find the `vendor/composer/installed.json`

If this is the case and I want to use this tool, my only option as I see it is, to change the `vendor`-folder and do a new minor release, and then add the tool. 

Is my assumption correct?

**Comment by Ocramius** [comment]
Yep, a `composer install` is being simulated in both `--from` and `--to` refs (in your case, `9.1.0` and `HEAD`, if I understood correctly), so the tool either needs to become smart enough to understand `vendor-dir` or you have to start checking from the point in your git history where a conventional `vendor` location is used.

**Comment by tomasnorre** [comment]
Thanks for a fast reply.
Will see if I can come up with a solution that allows non-standard vendor-dirs.

**Comment by Ocramius** [comment]
Related paths here:


## Installation path is passed to `MakeLocatorForInstalledJson` here:

https://github.com/Roave/BackwardCompatibilityCheck/blob/20c0e653865822ecf836bd249810dea8f677a864/src/LocateDependencies/LocateDependenciesViaComposer.php#L58

That is part of `BetterReflection`: https://github.com/Roave/BetterReflection/blob/df8a13c8aafc5036d2c65884acd02d006905a433/src/SourceLocator/Type/Composer/Factory/MakeLocatorForInstalledJson.php#L30

Improving the class in upstream BetterReflection to consider `vendor-dir` should do the trick:

https://github.com/Roave/BetterReflection/blob/df8a13c8aafc5036d2c65884acd02d006905a433/src/SourceLocator/Type/Composer/Factory/MakeLocatorForInstalledJson.php#L40

**Comment by tomasnorre** [comment]
This can be closed then, as this will be solved with the next release of roave/better-reflection (4.12.x)

**Comment by tomasnorre** [comment]
Oh. You already released it. That's fast. 
Thanks

**Comment by Ocramius** [comment]
Automation FTW! 

Spent my damn summer on https://github.com/laminas/automatic-releases :D

**Comment by Ocramius** [comment]
@tomasnorre just to verify: this works now?

**Comment by tomasnorre** [comment]
I'm having some composer requirement conflicts. Will let you know when I get them resolved.

**Comment by tomasnorre** [comment]
Still don't look like it's working, but can be an error on my side, didn't have time to debug to find the mistake. 

But at least I get the newest version, so in theory it should haven been fixed. 
```shell
- Installing roave/better-reflection (4.12.0): Extracting archive
- Installing roave/backward-compatibility-check (5.0.0): Extracting archive
```
Will dig more into this when I find some time.

**Comment by tomasnorre** [comment]
The problems are summed up here. 
https://github.com/Roave/BetterReflection/issues/714
