### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by WyriHaximus** [Roave/BackwardCompatibilityCheck#283]
Aside from #264, is there anything else that is blocking a PHP 8 compatible release? 

P.S. This is a tracking issue for a release that supports PHP 8.

**Comment by asgrim** [comment]
I think BR (which this depends on) already supports PHP 8, but yeah the named params BC break is a big one that will need to go in. Sorry kinda dropped the ball there :/

**Comment by Ocramius** [comment]
BetterReflection needs major work: https://github.com/Roave/BetterReflection/issues/701

**Comment by asgrim** [comment]
> I think BR (which this depends on) already supports PHP 8,

clearly this is fake news

**Comment by sebastianbergmann** [comment]
Any update on this? Thanks!

**Comment by Ocramius** [comment]
@sebastianbergmann no work happening here ATM - too much stuff to maintain, and too little time to get it done.

Roave/BetterReflection#701 is still the major issue here.

**Comment by ktomk** [comment]
If you're pushy, you can try to just run it. Mind the installer output the configured PHP version has all the extensions, the warnings for the PHP versions I did ignore and it all worked.

Replace :dev-master or any of the composer config options in the composer related goals to control with which version you would like to run.

Display is optimized for composer 2, log has all standard error, standard output is unfiltered.

https://gist.github.com/ktomk/30149eec13fa6ed7374cdae5d2ef86f9

**Comment by Ocramius** [comment]
Just beware that it will crash and/or misreport on the first usages of PHP
8 built-ins.

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by ktomk** [comment]
the code I test it with is not of php 8 syntax, true. the composer 2 message nugged me, so I just put in some force.

**Comment by Ocramius** [comment]
This is being tracked in #324

**Comment by Ocramius** [comment]
FWIW, it is impossible to support `php:^7.4` together with `php:~8.0.0` and `php:~8.1.0`.

The changes in reflection in PHP are such an amazing pain in the butt that we simply won't be able to get there in any reasonable time: instead, this tool will need to run from PHP 8.0 or PHP 8.1 only.

It will still be able to analyze PHP 7.4 (and earlier) code, but running it will require a newer environment.
