### ISSUE TITLE
Ignoring files and folders by pattern?

### ISSUE THREAD

**Issue by burzum** [Roave/BackwardCompatibilityCheck#303]
This tool would be very useful for us if it had this feature. :) Any plans on adding this? I don't mind to contribute the feature if you would accept it.

We have a module based architecture and we do semver with our modules. We have a specification for what we consider to be public API in these modules. Everything else is allowed to change because it is behind the facade. So we wouldn't need to BC check this code.

**Comment by Ocramius** [comment]
Heyo: what you declare in your "autoload" section is public API by default,
and that's how it's understood by the community at large too.

If you need it to be internal only, mark it ***@***.***` to prevent outside
usage.

**Comment by burzum** [comment]
As I wrote within our internal constraints and the way our architecture works (modules are only allowed to access other modules facade through a bridge) the only API of a module we consider public and want to check for BC breaks is the facade. If you touch anything else your fault, we only guarantee that the facade is stable. This is the exact use case I want to use this tool for.

**Comment by Ocramius** [comment]
You should really declare everything internal except for the facade then 👍
