### ISSUE TITLE
Roave\BetterReflection\SourceLocator\Type\Composer\Psr\Exception\InvalidPrefixMapping thrown on required library

### ISSUE THREAD

**Issue by JanPietrzyk** [Roave/BackwardCompatibilityCheck#336]
Hi,

When running the command I get a `InvalidPrefixMapping` Exception from BetterReflection. One of the included Packages has an addition PSR-4 Namespace, that is actually not included in the package. 

While I think this exception is sensible from BetterReflection's point of view, I think it should be handled in BackwardCompatibility check. Composer itself does not seem to see an issue here.

The package in question is `marc1706/fast-image-size` which has a `export-ignore` setting in its [.gitattributes](https://github.com/marc1706/fast-image-size/blob/master/.gitattributes) file that removes the test directory.

**Comment by Ocramius** [comment]
This is likely thrown way before this tool started its actual runtime, and while it is still setting up source and dependency paths.

Indeed, it is quite strict about how the sources and dependencies are to be scanned (all declared paths must be valid).

**Comment by JanPietrzyk** [comment]
@Ocramius thank you for your response. Yes you're right, it happens during preparation.

```
In InvalidPrefixMapping.php line 28:
                                                                                                                                                                                      
  [Roave\BetterReflection\SourceLocator\Type\Composer\Psr\Exception\InvalidPrefixMapping]                                                                                             
  Provided path "FastImageSize\tests\" for prefix "/tmp/api-compare-532e58f82da70f592f5e1837cedf2260f7a45a7b_619c8b6784c88/vendor/marc1706/fast-image-size/tests" is not a directory  
                                                                                                                                                                                      

Exception trace:
  at /app/vendor-bin/roave-backward-compatibility-check/vendor/roave/better-reflection/src/SourceLocator/Type/Composer/Psr/Exception/InvalidPrefixMapping.php:28
 Roave\BetterReflection\SourceLocator\Type\Composer\Psr\Exception\InvalidPrefixMapping::prefixMappingIsNotADirectory() at /app/vendor-bin/roave-backward-compatibility-check/vendor/roave/better-reflection/src/SourceLocator/Type/Composer/Psr/Psr4Mapping.php:116
 Roave\BetterReflection\SourceLocator\Type\Composer\Psr\Psr4Mapping::assertValidMapping() at /app/vendor-bin/roave-backward-compatibility-check/vendor/roave/better-reflection/src/SourceLocator/Type/Composer/Psr/Psr4Mapping.php:38
 Roave\BetterReflection\SourceLocator\Type\Composer\Psr\Psr4Mapping::fromArrayMappings() at /app/vendor-bin/roave-backward-compatibility-check/vendor/roave/better-reflection/src/SourceLocator/Type/Composer/Factory/MakeLocatorForInstalledJson.php:107
 Roave\BetterReflection\SourceLocator\Type\Composer\Factory\MakeLocatorForInstalledJson->__invoke() at /app/vendor-bin/roave-backward-compatibility-check/vendor/roave/backward-compatibility-check/src/LocateDependencies/LocateDependenciesViaComposer.php:58
 Roave\BackwardCompatibility\LocateDependencies\LocateDependenciesViaComposer->__invoke() at /app/vendor-bin/roave-backward-compatibility-check/vendor/roave/backward-compatibility-check/src/Command/AssertBackwardsCompatible.php:163
 Roave\BackwardCompatibility\Command\AssertBackwardsCompatible->execute() at /app/vendor-bin/roave-backward-compatibility-check/vendor/symfony/console/Command/Command.php:299
 Symfony\Component\Console\Command\Command->run() at /app/vendor-bin/roave-backward-compatibility-check/vendor/symfony/console/Application.php:978
 Symfony\Component\Console\Application->doRunCommand() at /app/vendor-bin/roave-backward-compatibility-check/vendor/symfony/console/Application.php:295
 Symfony\Component\Console\Application->doRun() at /app/vendor-bin/roave-backward-compatibility-check/vendor/symfony/console/Application.php:167
 Symfony\Component\Console\Application->run() at /app/vendor-bin/roave-backward-compatibility-check/vendor/roave/backward-compatibility-check/bin/roave-backward-compatibility-check.php:313
 Roave\ApiCompareCli\{closure}() at /app/vendor-bin/roave-backward-compatibility-check/vendor/roave/backward-compatibility-check/bin/roave-backward-compatibility-check.php:314
 require_once() at /app/vendor-bin/roave-backward-compatibility-check/vendor/roave/backward-compatibility-check/bin/roave-backward-compatibility-check:6
```

While this would be easy to fix in BetterReflection's `MakeLocatorForInstalledJson`, it is kind of hard to do it here. 

What are your thoughts, is this an issue in BetterReflection?

**Comment by Ocramius** [comment]
It is potentially something that requires a "custom source locator".

In practice, this means taking this specific file, and rewriting/copying it: https://github.com/Roave/BackwardCompatibilityCheck/blob/d25bf3bdcf8427b5c382cfb06a281583143cf833/bin/roave-backward-compatibility-check.php

This is the problematic bit for you, and that file is thought to be the configuration/entry-point for this tool: https://github.com/Roave/BackwardCompatibilityCheck/blob/d25bf3bdcf8427b5c382cfb06a281583143cf833/bin/roave-backward-compatibility-check.php#L68-L81

The idea is to have a "lax source locator" dropped in there.

Alternatively, create the paths that are missing (as a fix, until upstream `marc1706/fast-image-size` fixes their mappings /cc @marc1706 ) in that closure.

**Comment by JanPietrzyk** [comment]
I think this can be closed for now. I have found a sufficient workaround. Thanks @Ocramius

**Comment by lulco** [comment]
Hi @Ocramius, I have similar issue with package whichbrowser/parser. Composer installs the package without any problem, so I just want to ask you. Why are Roave packages "more Catholic than the Pope"? Why these non-existing directories are not just skipped?

**Comment by Ocramius** [comment]
... and why didn't you report the issue (and fix it) in `whichbrowser/parser`, instead of coming here with that tone?
