### ISSUE TITLE
Allow to exclude directories / classes

### ISSUE THREAD

**Issue by JanPietrzyk** [Roave/BackwardCompatibilityCheck#339]
I'm currently working on a project that contains example code, template code, documentation and generator scripts. These are separated from the production code and not part of the BC promise. However, they are not marked `@internal`, because documentation takes care of this.

I would prefer to maintain a Blacklist for files and directories to exclude from BC Testing. This would, by the way, make it a lot easier for us to incrementally adopt this tool.

Since I could not find an issue where this was already discussed, I am wondering whether this idea occurred to you before or if there is another way, which I am not aware of.

**Comment by Ocramius** [comment]
> However, they are not marked @internal, because documentation takes care of this.


Marking them as `@internal` is the proper way to deal with this, as it is the deny-list (let's avoid/deprecate the "blacklist" terminology) that you are looking for.

**Comment by JanPietrzyk** [comment]
> (let's avoid/deprecate the "blacklist" terminology

Good point, sorry.... Bad habit...  

@Ocramius  While I understand that `@internal` is the proper way. This is for BC (ironically) reasons not an option at the moment. I am wondering what the path to integrating this tool into the CI environment looks like.

**Comment by Ocramius** [comment]
> This is for BC (ironically) reasons not an option at the moment. 

Shouldn't those classes then be covered by the tool itself? :thinking:

**Comment by JanPietrzyk** [comment]
> Shouldn't those classes then be covered by the tool itself? thinking

Yep they are. Basically we want to add the tool first and then change the sources accordingly, and in sync with the release plan. At least in my experience that's the better approach because we can verify if it works for us in a shorter amount of time.

I have already forked the project and will just implement the missing bits. If I get you correctly you are not interested in a PR in this context?

**Comment by Ocramius** [comment]
> If I get you correctly you are not interested in a PR in this context?

Depends on scope: in my opinion, implementing a filter in userland is better.

Specifically, I think that we could improve the project in the binary/startup.

This section is usually more "customization-heavy":

https://github.com/Roave/BackwardCompatibilityCheck/blob/d25bf3bdcf8427b5c382cfb06a281583143cf833/bin/roave-backward-compatibility-check.php#L62-L81

The block after it is a more default "set of standard rules":

https://github.com/Roave/BackwardCompatibilityCheck/blob/d25bf3bdcf8427b5c382cfb06a281583143cf833/bin/roave-backward-compatibility-check.php#L82-L307

If we move the second block into an abstraction, perhaps we can make the bootstrapping/customization less painful for userland?

**Comment by JanPietrzyk** [comment]
Finlay, got it working. I think we will now start to evaluate the tool and see how good it works in our use case. Thank you very much @Ocramius !

Could happen that I will add some more use cases here, I am not sure yet.

BTW I had to make adjustments in three classes

`\Roave\BackwardCompatibility\CompareClasses`

* Add ability to mute certain errors (eg. a `__DIR__` constant as a default value)
* Add a failure change if the `$pastSourcesReflector` can't reflect a class

`\Roave\BackwardCompatibility\Factory\ComposerInstallationReflectorFactory`

* Decorate the locator with a filter

`\Roave\BackwardCompatibility\LocateDependencies\LocateDependenciesViaComposer`

* Fix the Bug from #336

**Comment by Ocramius** [comment]
> Add ability to mute certain errors (eg. a __DIR__ constant as a default value)

This is likely fixed in `roave/better-reflection:5.0.x-dev`

 > Add a failure change if the `$pastSourcesReflector` can't reflect a class

This could probably be worth adding directly to this codebase? 

 > Decorate the locator with a filter

Overall the approach I endorse, absolutely.

If you feel like your filter could work here too, perhaps throw it this way (in a comment, at first), and we may include it later on.
