### ISSUE TITLE
Support github output format

### ISSUE THREAD

**Issue by Ocramius** [Roave/BackwardCompatibilityCheck#342]
This application/library is 99% of the time going to be used on libraries hosted here on GitHub - we may as well provide the GitHub Actions output format by default.

See https://github.com/vimeo/psalm/blob/8bc71fcf855a0908b913b42b740be6c98960d994/src/Psalm/Report/GithubActionsReport.php
See https://github.com/infection/infection/blob/f60fbc5b4175ea8eb1c825546970d7c1578d23df/src/Logger/GitHubAnnotationsLogger.php
See https://github.com/symfony/console/blob/3e7ab8f5905058984899b05a4648096f558bfeba/CI/GithubActionReporter.php
See https://github.com/staabm/annotate-pull-request-from-checkstyle/blob/5b0bb3c69b9c129e81ea85321c09577adf952dd7/cs2pr#L123

**Comment by staabm** [comment]
Both mentioned links are missing some escaping .. better look e.g. here https://github.com/staabm/annotate-pull-request-from-checkstyle/blob/5b0bb3c69b9c129e81ea85321c09577adf952dd7/cs2pr#L123

**Comment by Ocramius** [comment]
Eh, escaping is not that critical in log output :D 

Still, thx for the reference!

**Comment by Ocramius** [comment]
Beware: this is not necessarily a small change, as it may require collecting the reflection symbols in the produced `BCBreak` instances

**Comment by Pierstoval** [comment]
My 2cents: It's possible to enable it automatically by detecting Github Action via environment variables, so you keep your defaults, but if no specific format is passed in CI, you can detect Github and use it

Edit: check these: https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables

**Comment by williamdes** [comment]
You will find all the formats you would like to have here (credits to phpstan for the code): https://github.com/code-lts/cli-tools/tree/main/src/ErrorFormatter

**Comment by Ocramius** [comment]
Handled in #371
