### ISSUE TITLE
Allow release versions such as `v1.2.3` and `release-1.2.3` (as well as other patterns recognized by composer)

### ISSUE THREAD

**Issue by Ocramius** [Roave/BackwardCompatibilityCheck#37]
Ref: https://github.com/Roave/ApiCompare/pull/35#discussion_r181588570

**Comment by ntzm** [comment]
Should this be something that is dealt with in nikolaposa/version?

**Comment by Ocramius** [comment]
@ntzm yeah

**Comment by ntzm** [comment]
I opened an issue here: https://github.com/nikolaposa/version/issues/12, looks like it won't be until 3.0 that it's considered

**Comment by ciaranmcnulty** [comment]
This is pretty important, AFAIK `v1.2.3` was not only supported it was _encouraged_ by composer, at least at one stage

**Comment by Ocramius** [comment]
Talked with @nikolaposa in person about this, and it will likely happen when he has time and willpower (PHP Serbia aftermath first)

**Comment by nikolaposa** [comment]
Support for `v1.2.3` has already been implemented in https://github.com/nikolaposa/version/releases/tag/3.0.0 (15: Relaxed version parsing). I'll consider adding support for `release-` prefix for `3.1.0`. 

btw Is there any other prefix besides `v-` and `release` that would be worth considering?

**Comment by ntzm** [comment]
Looking through the composer source, seems it's just [`release-`](https://github.com/composer/composer/blob/4d8b9be5b6a0bda0a3d24c0a6ff89d7ccb26f715/src/Composer/Repository/VcsRepository.php#L153) and [`v`](https://github.com/composer/composer/blob/4d8b9be5b6a0bda0a3d24c0a6ff89d7ccb26f715/src/Composer/Repository/VcsRepository.php#L254)

**Comment by nikolaposa** [comment]
I mean, if I'm going to introduce that change, I would like it to be something that is not only Composer-specific, but more general, hence the question.

**Comment by alcohol** [comment]
Composer does not strictly follow semver formatting. If you look at https://github.com/composer/semver (specifically, the tests) you'll see it is very similar but there are a few deviations for legacy reasons. I think the `v` prefix is the only prefix we support. The `release-` prefix is not supported btw, but it is stripped for legacy reasons AFAIK.

**Comment by nikolaposa** [comment]
Version parsing was relaxed to supports both `v` and `release-` Composer-recognized prefixes in `nikolaposa/version:^3.2.0` so I assume this one is fixed?

**Comment by Ocramius** [comment]
Still need a way to get the symbol name back though, as otherwise we cannot really run a `git checkout` command with a valid REF

**Comment by nikolaposa** [comment]
Got it. Can you refer me to some relevant places in code base so I can become more familiar with entire flow and how/whether `Version` is used in conjunction with other components, i.e. `VersionCollection`?

**Comment by Ocramius** [comment]
I think `VersionCollection` is only used during sorting, lemme dig up the relevant code location

**Comment by Ocramius** [comment]
This is where we need to preserve the original tag name: https://github.com/Roave/BackwardCompatibilityCheck/blob/master/src/Command/AssertBackwardsCompatible.php#L229

**Comment by nikolaposa** [comment]
Oh, I see the problem now. Versions retrieved from the repository are successfully parsed but their initial form is lost, so casting them back to string yields undesired result.

I'll see what I can do. 🤔 But everything suggests that I'll have to relax my strict adherence to semver.org and the idea that prefix is not part of the version number. Encapsulating that behaviour in a new object as I suggested [here](https://github.com/Roave/BackwardCompatibilityCheck/pull/179#issuecomment-566187100) would make `VersionCollection` uselues for your scenario. This will be a fun weekend. :)

**Comment by Ocramius** [comment]
It would also break (pseudo-code) `Version::fromString('1.2.3') == Version::fromString('v1.2.3')`, so only `->equals()` is viable now.

I also noticed an edge case: we could have duplicate versions (already happened in doctrine) due to `v1.2.3` and `1.2.3` both being valid tags on a repository

**Comment by nikolaposa** [comment]
Something like this: https://github.com/nikolaposa/version/commit/87ab65225589fb1297be161f659bca5fed780eac could definitely solve the part with constructing and casting Version from/to string. But comparison problem would still remain as the `$prefix` is used solely for the purpose of preserving the original context.

**Comment by Ocramius** [comment]
Seems about right

**Comment by nikolaposa** [comment]
I'm not a fan of the idea of `getPrefix()` becoming part of `Version` public API, so as an alternative solution I could introduce `VersionNumber` that would be _the_ SemVer-compliant object, and have the existing `Version`, with the same API + `getPrefix()` behaviour proxy to it. 

That way I could avoid making some serious BC breaks, as `Version` behaviour would remain the same from the outside.

**Comment by nikolaposa** [comment]
I was thinking about `v1.2.3 == 1.2.3` scenario. While it might be true that those are not the same versions, I have no idea what reasoning is valid in the case of other comparisons:

```
$v1 = Version::fromString('v1.2.3');
$v2 = Version::fromString('release-1.2.3');
var_dump($v1->isEqualTo($v2)); //false
var_dump($v1->isGreaterThan($v2)); //???
var_dump($v1->isLessThan($v2)); //???
```

If it's not equal, is it higher, is it lower? You can't really tell, because prefix does not carry any semantical meaning, unlike pre-release or build extensions for example that are compared lexically in ASCII sort order.

**Comment by Ocramius** [comment]
They are equal, but don't have the same state, hence == doesn't work
