### ISSUE TITLE
Extension system

### ISSUE THREAD

**Issue by shyim** [Roave/BackwardCompatibilityCheck#377]
Hey,

we're currently adding custom checks into this tool using composer patches. I feel really dirty to add a custom check into the list of https://github.com/Roave/BackwardCompatibilityCheck/blob/6.1.x/bin/roave-backward-compatibility-check.php#L86

I guess a simple extension system could help here already to add custom checks.

What I think is:

- A interface with methods like `getClassChecks` `getMethodChecks`... which returns the instances
- The implemented class can be provided using `extra` part in the composer.json
- We use composer to look them up to register them in the `roave-backward-compatibility-check.php` or maybe move the core things to the same interface based thingy?

**Comment by Ocramius** [comment]
This block of code is literally **the** configuration of this utility:

https://github.com/Roave/BackwardCompatibilityCheck/blob/d4c84f0b52f2361a517bfa6c9f992311d4a5d6ce/bin/roave-backward-compatibility-check.php#L82-L311

The current way you customize it is by copying the whole `roave-backward-compatibility-check.php` and writing your own version of it. The piece that is usually "in common" is this:

https://github.com/Roave/BackwardCompatibilityCheck/blob/d4c84f0b52f2361a517bfa6c9f992311d4a5d6ce/bin/roave-backward-compatibility-check.php#L55-L81

Even then, it is not uncommon that the `from`/`to` source locators are customized by end-users.

Requiring `vendor/autoload.php` is generally a one-liner, in custom projects:

https://github.com/Roave/BackwardCompatibilityCheck/blob/d4c84f0b52f2361a517bfa6c9f992311d4a5d6ce/bin/roave-backward-compatibility-check.php#L38-L53

I thought about how to make this "easier to customize", but in practice, it is better to:

 1. copy the file
 2. adjust as needed
 3. have it covered by your own static analysis checks, which will pick up any BC breaks/incompatibilities

So don't feel dirty about it: it's still the best way forward, and if you needed to change one tiny check 10 levels deep in the structure, you still have to rewrite the whole instantiation chain anyway :) 

One simplification I thought of is unifying `bin/roave-backward-compatibility-check.php` and `bin/roave-backward-compatibility-check`, but need to check if the non-`.php` file can still be statically analyzed.
