### ISSUE TITLE
Allow filtering classes, interfaces, traits, methods, functions, properties and constants annotated via `@api` and `@internal`

### ISSUE THREAD

**Issue by Ocramius** [Roave/BackwardCompatibilityCheck#51]

**Comment by Ocramius** [comment]
Note: removing `@api` or adding `@internal` are both to be considered BC breaks.

**Comment by Ocramius** [comment]
@slash3b this is the issue we talked about the other day

**Comment by slash3b** [comment]
Oh, thanks! I took a look over the weekend and had no idea what is going on.
Hope this one helps : )
