### ISSUE TITLE
Using this package in Bitbucket Pipelines

### ISSUE THREAD

**Issue by mad-briller** [Roave/BackwardCompatibilityCheck#653]
First things first, this package is a genius idea, thank you for the work on it.

However we are trying to integrate it with Bitbucket pipelines and insights, but the output formats available are awkward for us to consume in this context.

`github-actions` is the most machine-readable but that requires us to implement a custom parser for the format to transform into the format required by bitbucket (unless there is a php implementation to parse this already? i had no luck finding one)

would Roave be open to a PR that implemented a `json` formatter type that would make it simpler for us to consume?

thanks for your time

**Comment by Ocramius** [comment]
Sure thing, but if we provide a JSON formatter, it must come with an associated JSON Schema

**Comment by Ocramius** [comment]
BTW, you can check for more standard formats, like XUnit and similar: some of them work well with both Bitbucket and GitLab

**Comment by mad-briller** [comment]
Bitbucket accepts those as test-reports but won't use them for the purpose of annotating pull requests unfortunately; annotating pull requests in the bitbucket world requires making api requests, which is very awkward. 

However it still stands to reason that we could use a more standard format, i will look into JUnit as it's one i'm more familiar with. Don't know why i didn't think of that first, thanks!

**Comment by Ocramius** [comment]
Yeah, even if the reporting requires making API calls, tooling for that probably already exists, given a good input format.

**Comment by mad-briller** [comment]
thanks for your help with this @Ocramius

**Comment by Ocramius** [comment]
Thank you for implementing this with a clean design! 👍
