### ISSUE TITLE
`Roave\BetterReflection\Reflection\ReflectionClass` "XXX" could not be found in the located source

### ISSUE THREAD

**Issue by bendavies** [Roave/BackwardCompatibilityCheck#67]
Hey there,

Great tool! Excited to use this!
I tried running this on https://github.com/api-platform/core on the 2.2 branch:
`bin/roave-backward-compatibility-check --from=v2.2.6 --to=HEAD`
but receive:
```
In IdentifierNotFound.php line 30:

  Roave\BetterReflection\Reflection\ReflectionClass "Doctrine\DBAL\Types\Type" could not be found in the located source
```

Couldn't immediately work out the problem to fix myself, so tracking an issue.

**Comment by Ocramius** [comment]
This usually happens when a parameter type or a return type cannot be resolved. Try running `maglnet/ComposerRequireChecker` to see if some dependencies are not strictly part of the project.

**Comment by bendavies** [comment]
I see yes, dbal was a dev dependency. maybe it should be a suggested dep, and this tool should install suggestions?

**Comment by bendavies** [comment]
huh, i thought composer had a way to install suggestions, but apparently not.

**Comment by bendavies** [comment]
how about making `BackwardCompatibilityCheck` install dev dependencies?
This issue is that api-platform only enables some features if certain non mandatory deps are installed, but ofcourse they included in `require-dev` for testing purposes.

**Comment by yaroslavche** [comment]
Same here. `doctrine/dbal` is just dev dependency.
```
[BC] SKIPPED: Roave\BetterReflection\Reflection\ReflectionClass "Doctrine\DBAL\Types\Type" could not be found in the located source
```
[Travis failed build](https://travis-ci.org/yaroslavche/BitMask/jobs/541668193)
What i've missed?

**Comment by Ocramius** [comment]
Please run `maglnet/composer-require-checker` over your codebase.

**Comment by yaroslavche** [comment]
```
yaroslav@ip:~/projects/BitMask> composer-require-checker check
ComposerRequireChecker unknown-development
The following unknown symbols were found:
+------------------------------------------+--------------------+
| unknown symbol                           | guessed dependency |
+------------------------------------------+--------------------+
| Doctrine\DBAL\Types\Type                 |                    |
| Doctrine\DBAL\Platforms\AbstractPlatform |                    |
+------------------------------------------+--------------------+
```
Used [here](https://github.com/yaroslavche/BitMask/blob/master/tests/Doctrine/Types/BitMaskTypeTest.php). And `doctrine\dbal` supposed to be dev dependency (if need to use custom type - it will expect that project already have installed dbal). So, I think, I am not allowed to do like this?

**Comment by Ocramius** [comment]
Correct: you'd have to split out those classes into a separate package which has DBAL in `"require"` (not `"require-dev"`)

In practice, what can happens is that `Doctrine\DBAL\Types\Type` has a BC break, and your package transmits that BC break by transitivity.
