### ISSUE TITLE
Broken autoload when in vendor/bin

### ISSUE THREAD

**Issue by ciaranmcnulty** [Roave/BackwardCompatibilityCheck#70]
I installed this on a project that doesn't have a specified bin-dir

```bash
> vendor/bin/roave-backward-compatibility-check 
PHP Fatal error:  Uncaught RuntimeException: Could not find Composer autoload.php in /my/project/vendor/roave/backward-compatibility-check/bin/roave-backward-compatibility-check.php:292
```

Debugging the loop in `roave-backward-compatibility-check.php` it's searching the following locations:

```
/my/project/vendor/roave/backward-compatibility-check/bin/../vendor/autoload.php
/my/project/vendor/roave/backward-compatibility-check/bin/../autoload.php
```

Of course neither contain the project deps because they're all higher up in `/my/project/vendor`

We tackle the similar issue in phpspec by also looking at paths relative to `getcwd()` but it's not that great a solution.

At the least, you can document that `bin-dir` needs to exist _and_ it needs to be one dir below the project root

**Comment by Ocramius** [comment]
By default, `bin-dir` exists and defaults to `vendor/bin`: what is your `composer.json` like?

Also, I can see that this will further fail due to `vendor` not being in a standard location, and that will cause dependencies to not be found when the static analysis steps are actually run.

**Comment by ciaranmcnulty** [comment]
sorry, I meant I hadn't overridden it (https://github.com/phpspec/phpspec/blob/master/composer.json) - I'm executing it from `vendor/bin/roave-backward-compatibility-check`

**Comment by Ocramius** [comment]
Can you attempt a standalone installation of the tool and then running it from the phpspec cwd for now?

**Comment by Ocramius** [comment]
And yep, will fix in a few 👌

**Comment by ciaranmcnulty** [comment]
If I do a complete separate checkout, run composer update there, then it executes (I get a different error I'll try and debug, to do with how it executes git)

Note that composer global install also won't work currently:

```
> composer global require roave/backward-compatibility-check
[...]
> ~/.composer/vendor/bin/roave-backward-compatibility-check 
PHP Fatal error:  Uncaught RuntimeException: Could not find Composer autoload.php in [~]/.composer/vendor/roave/backward-compatibility-check/bin/roave-backward-compatibility-check.php:289
```

**Comment by Ocramius** [comment]
Aye, I think we never tried/throught of it as a dependency. Sending a patch
within today 👌

**Comment by ciaranmcnulty** [comment]
It might be worth adding a couple of smoke tests for different install methods?

I poked around some other tools

https://github.com/phpactor/phpactor/blob/develop/bin/phpactor#L11-L12
https://github.com/sebastianbergmann/phpunit/blob/master/phpunit#L30

Nobody seems to agree on the search path, and people with weird `bin-dir` or `vendor-dir` are going to have a bad time in all cases :-/

Maybe this is why PHAR is the future

**Comment by Ocramius** [comment]
Until PHAR installation goes through a lock/SAT mechanism and namespace
scoping, it will be generally avoided on my side.

**Comment by Ocramius** [comment]
Handled in #71
