### ISSUE TITLE
Adding a type to a property in a final class should not break BC

### ISSUE THREAD

**Issue by jack-worman** [Roave/BackwardCompatibilityCheck#715]
If we have class:
```php
final class Foo {
    public $prop1;
}
```
and update it to be:
```php
final class Foo {
    public string $prop1;
}
```

There should be no BC break. Right?

**Comment by Ocramius** [comment]
It's still a BC break, since consumers of that class:

 * can no longer read uninitialised state (`null` by default)
 * can no longer write non-`string` values to that property
