### ISSUE TITLE
Git error when running without --from option

### ISSUE THREAD

**Issue by ciaranmcnulty** [Roave/BackwardCompatibilityCheck#72]
Steps to reproduce:

1. check out `phpspec/phpspec`
2. add this tool to composer requires and update
3. run `vendor/bin/roave-backward-compatibility-check`

Error:

```
[Symfony\Component\Process\Exception\ProcessFailedException]                     
  The command "'git' 'rev-parse' ''" failed.                                       
                                                                                   
  Exit Code: 128(Invalid exit argument)
```

The input parameter `--from` is optional so its default value is `NULL`. this is explicitly cast to a string `''` in `AssertBackwardsCompatible::parseRevisionFromInput`, but the implementation of `GitParseRevision` then builds a the CLI with an empty string, which breaks as above

**Comment by ciaranmcnulty** [comment]
oh I see the problem, will PR

**Comment by Ocramius** [comment]
Handled in #73
