### ISSUE TITLE
Fatal error due to memory limit

### ISSUE THREAD

**Issue by jenschude** [Roave/BackwardCompatibilityCheck#75]
```
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 9437184 bytes) in vendor/composer/composer/src/Composer/Repository/ComposerRepository.php on line 565
```

Default configuration for php cli runtime is 128M.

For larger code bases it's very likely to hit this limit easily. Fixed the issue locally by disabling the memory limit in the `bin/roave-backward-compatibility-check.php` with `ini_set('memory_limit', '-1');`

**Comment by Ocramius** [comment]
This is normal, but the tool will in no way touch your configuration. Use `-dmemory_limit=2G`.

**Comment by jenschude** [comment]
Composer had the same problems and added a helper method in their binary see https://github.com/composer/composer/blob/master/bin/composer#L21-L51

**Comment by Ocramius** [comment]
Yes, and `composer` is a tool supposed to be used by everyone, while this tool is aimed at library developers, which already know how to deal with these basic problems.

I wholeheartedly disagree with tampering with the runtime environment in any way, so you won't see things like "disabling xdebug", "enabling error reporting" or such in any of my repositories :-)

**Comment by jenschude** [comment]
I see your point.

But composer needs at least 1.5GB to run properly. So maybe it would help to add a small addition to the documentation.

**Comment by Ocramius** [comment]
> small addition to the documentation.

Probably a good idea to add it to the command's `--help` :+1:
