### ISSUE TITLE
Allow running backwards-compatibility check in repository without tags

### ISSUE THREAD

**Issue by localheinz** [Roave/BackwardCompatibilityCheck#756]
It would be great if I could run this tool in a repository that does not have any releases yet.

Running

```shell
composer require --dev roave/backward-compatibility-check:^8.4.0
```

followed by

```shell
vendor/bin/roave-backward-compatibility-check
```

in a repository that does not have any tags yet yields

```console
In invariant_violation.php line 16:

  Could not detect any released versions for the given repository


roave-backwards-compatibility-check:assert-backwards-compatible [--from [FROM]] [--to TO] [--format [FORMAT]] [--install-development-dependencies]
```

It would be great if I could run this tool in a repository that does not have any tags yet. 

This could include 

- repositories that work as GitHub repository templates for a PHP package
- repositories for PHP packages that have not had any releases yet

What do you think?

Perhaps an option `--ignore-repository-without-tags` would make sense?

**Comment by Ocramius** [comment]
@localheinz define your own `--from=` and `--to=` with your own workflow: the default behavior looks for tags, and is IMO not to be complicated further

**Comment by Ocramius** [comment]
BTW, I suppose `--from=HEAD^1` and `--to=HEAD` could work, but I never tried :D

**Comment by localheinz** [comment]
Thank you, @Ocramius - [this](https://github.com/ergebnis/php-package-template/pull/1398) works for me!
