### ISSUE TITLE
New feature: Detect EnumCaseAdded as a BC break

### ISSUE THREAD

**Issue by bdsl** [Roave/BackwardCompatibilityCheck#767]
As far as I can tell this isn't something currently detected, but I think adding a new enum case should be considered a breaking change, as it will break any consuming code that was previously relying on being able to exhaustively handle all cases of an enum.

For instance consuming code will often use match with an enum, which will throw [UnhandledMatchError ](https://www.php.net/manual/en/class.unhandledmatcherror.php) if the enum cases is a new one.

Would people be interested in a PR to implement this check?

**Comment by Ocramius** [comment]
Yes please!
