### ISSUE TITLE
Changes in arguments representing array shapes

### ISSUE THREAD

**Issue by boesing** [Roave/BackwardCompatibilityCheck#795]
Hey guys,

I was working on [`laminas-cache`](https://github.com/laminas/laminas-cache/pull/311) recently where there is a config factory consuming an array configuration shape.
I dropped one possible array shape as it was just there to provide backwards compatibility.

- Having something removed from an array shape (which is sealed) should automatically be detected as BC break, no?
- Removing a possible shape in favor of another (which is incompatible with the shape before) should end up in a BC break as well, no?

Just want to gather some feedback. Thanks in advance.

**Comment by asgrim** [comment]
Hmm, good question. The limitation is the upstream `roave/better-reflection` here; unless I'm mistaken, I believe we actually removed support for docblock types; and thus I don't think we're aware of the shapes of arrays (only the native `ReflectionType` stuff is read, I think).

**Comment by boesing** [comment]
Ah, I was somehow thinking that better reflection was based on psalm but its php-parser.
That does not provide necessary array shape information and thus I guess it does not make sense to have that covered here.
Works for me 🤙🏼 
Thanks for the feedback.

**Comment by Ocramius** [comment]
@boesing in order to completely analyse types at that level, we would need to swap out `roave/better-reflection` for PHPStan or Psalm, completely moving expression type analysis there.
