### ISSUE TITLE
Removed constructor is not BC change

### ISSUE THREAD

**Issue by vjik** [Roave/BackwardCompatibilityCheck#799]
For example:

```php
final class A {
    public function test(): void
    {
        echo 'OK';
    }
};

$a = new A('asdf');
$a->test();
```

This code is OK.

**Comment by Ocramius** [comment]
Sounds reasonable.

We'd need to filter the BC issues around this location:

https://github.com/Roave/BackwardCompatibilityCheck/blob/8443e589184c18615282bb969cb21612651df110/bin/roave-backward-compatibility-check.php#L96

**Comment by Ocramius** [comment]
I'd still call it a BC issue, because constructors in PHP can (and sometimes are) called post-initialization.

```php
class Foo { function __construct() { var_dump("hello"); } }
$a = new Foo();
$a->__construct();
```

https://3v4l.org/PHtBQ

**Comment by Ocramius** [comment]
Note: calling `__construct` afterwards is mostly done in infrastructural layers, such as in https://github.com/Ocramius/ProxyManager/ or https://wiki.php.net/rfc/lazy-objects
