### ISSUE TITLE
Crash on non-standard scalar type names

### ISSUE THREAD

**Issue by Majkl578** [Roave/BackwardCompatibilityCheck#83]
```
$ vendor/bin/roave-backward-compatibility-check roa:ass --to=HEAD --from=eb73ac50b890bf8 lib
Comparing from eb73ac50b890bf8c26115ff5975fc6adf093dd0b to 02538d3f95e88eb397a5f86274deb2c6175c2ab6...
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 2 installs, 0 updates, 0 removals
  - Installing doctrine/lexer (v1.0.1): Loading from cache
  - Installing doctrine/annotations (v1.6.0): Loading from cache
Generating optimized autoload files

In Fqsen.php line 48:

  "\Doctrine\Common\Reflection\boolean." is not a valid Fqsen.
```

Reproducible with the command above in doctrine/reflection repo (HEAD=02538d3f95e88eb397a5f86274deb2c6175c2ab6, but issue comes from `--from` commit).

```
$ git grep boolean
lib/Doctrine/Common/Reflection/StaticReflectionParser.php:     * @var boolean.
lib/Doctrine/Common/Reflection/StaticReflectionParser.php:     * @var boolean
lib/Doctrine/Common/Reflection/StaticReflectionParser.php:     * @param boolean              $classAnnotationOptimize Only retrieve the class docComment.
```

**Comment by Xerkus** [comment]
On a side note, `boolean.` is invalid, no dot is allowed. PR should be opened against doctrine common.

https://github.com/doctrine/common/blob/c0c61c03258c2e3672376fb2eca4a20d0f0bd013/lib/Doctrine/Common/Reflection/StaticReflectionParser.php#L31

**Comment by Majkl578** [comment]
Dot is not a valid character for typename so it should not be parsed and considered as valid name in first place. Actually now you confused me and I am not sure whether "boolean" without dot works or not :)

**Comment by Ocramius** [comment]
I think that `boolean` is not allowed at all by php documentor - would need to check it (yes, the Fqsen thing comes from PHPDocumentor).

Also, I'll need to add something that deals with crashes: can't have the entire tool crash because of a mistake that is deeply nested somewhere in a detail of a codebase.

**Comment by Majkl578** [comment]
@asgrim That commit is from doctrine/reflection: https://github.com/doctrine/reflection/commit/02538d3f95e88eb397a5f86274deb2c6175c2ab6

```
cd /tmp
git clone git@github.com:doctrine/reflection doctrine-reflection
cd doctrine-reflection
composer create-project roave/backward-compatibility-check:@dev
./backward-compatibility-check/bin/roave-backward-compatibility-check roa:ass --to=HEAD --from=eb73ac50b890bf8 lib
```

```
Comparing from eb73ac50b890bf8c26115ff5975fc6adf093dd0b to d1db8cee08bd5efe73b7270f3ed716626f0e2c92...

[...]

In Fqsen.php line 48:
                                                                
  "\Doctrine\Common\Reflection\boolean." is not a valid Fqsen.
```

**Comment by asgrim** [comment]
Ahh sorry, I just saw `\Doctrine\Common` and stopped reading, checking now :)

**Comment by Majkl578** [comment]
Btw:
> I think that boolean is not allowed at all by php documentor - would need to check it (yes, the Fqsen thing comes from PHPDocumentor).

It is allowed: https://docs.phpdoc.org/guides/types.html
> **bool or boolean**
>    A variable that can only contain the state ‘true’ or ‘false’.

**Comment by asgrim** [comment]
Yeh it seems to be just the `.` that is the issue, which is coming upstream from the phpdocumentor library :/ not really sure how to handle this as obviously you can't change the commit... :/

**Comment by Majkl578** [comment]
Since this tool is meant to compare a past and the current revision, I don't think your argument is valid. Yes, it may be bool _now_, but it wasn't back then. This issue is a great example of that.

**Comment by Ocramius** [comment]
Note: while the tool will detect an error here, it will no longer crash (as per `4.0.0` or `3.0.0`, I think). Closing here.
